apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "preview-operator.fullname" . }}-manager-role
  labels:
    {{- include "preview-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [configmaps, namespaces, resourcequotas, secrets, services]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [pods/log]
  verbs: [get]
- apiGroups: [""]
  resources: [events]
  verbs: [get, list, watch]
- apiGroups: [apps]
  resources: [deployments]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [batch]
  resources: [jobs]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [networking.k8s.io]
  resources: [ingresses, networkpolicies]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [networking.istio.io]
  resources: [virtualservices]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [platform.company.io]
  resources: [previews]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [platform.company.io]
  resources: [previews/finalizers]
  verbs: [update]
- apiGroups: [platform.company.io]
  resources: [previews/status]
  verbs: [get, patch, update]
- apiGroups: [platform.company.io]
  resources: [testplans]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [platform.company.io]
  resources: [testplans/status]
  verbs: [get, patch, update]
- apiGroups: [platform.company.io]
  resources: [testruns]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [platform.company.io]
  resources: [testruns/status]
  verbs: [get, patch, update]
- apiGroups: [platform.company.io]
  resources: [reconcileevents]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [platform.company.io]
  resources: [failurereports]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [platform.company.io]
  resources: [failurereports/status]
  verbs: [get, patch, update]
