apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "preview-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "preview-operator.labels" . | nindent 4 }}
