package evidence

import (
	"fmt"
	"sort"

	platformv1alpha1 "github.com/ihsenalaya/preview-operator/api/v1alpha1"
)

// Provenance relation names. The first four are W3C PROV relations; the last three
// are domain relations used by the failure evidence model. See
// docs/research/failure-provenance/failure-evidence-model.md.
const (
	relWasDerivedFrom    = "wasDerivedFrom"
	relWasGeneratedBy    = "wasGeneratedBy"
	relUsed              = "used"
	relWasAssociatedWith = "wasAssociatedWith"
	relWasInformedBy     = "wasInformedBy"
	relSupports          = "supports"
)

// graphBuilder accumulates provenance nodes and edges, de-duplicating nodes by ID.
type graphBuilder struct {
	nodes map[string]platformv1alpha1.ProvenanceNode
	edges []platformv1alpha1.ProvenanceEdge
}

func (g *graphBuilder) node(id string, kind platformv1alpha1.ProvenanceNodeKind, typ, label string) {
	if _, ok := g.nodes[id]; ok {
		return
	}
	g.nodes[id] = platformv1alpha1.ProvenanceNode{ID: id, Kind: kind, Type: typ, Label: label}
}

func (g *graphBuilder) edge(from, to, relation string) {
	g.edges = append(g.edges, platformv1alpha1.ProvenanceEdge{From: from, To: to, Relation: relation})
}

// BuildProvenanceGraph constructs the failure provenance graph for a bundle. The
// graph links the change context (pull request, commit, changed files), the
// preview resources, the captured evidence items, and the diagnosis, with PROV
// relations. Construction is deterministic: the same bundle yields the same graph.
func BuildProvenanceGraph(b *Bundle) *platformv1alpha1.ProvenanceGraph {
	if b == nil {
		return nil
	}
	g := &graphBuilder{nodes: map[string]platformv1alpha1.ProvenanceNode{}}

	// Agent and change-context entities.
	operatorID := "agent-operator"
	g.node(operatorID, platformv1alpha1.ProvenanceNodeAgent, "PreviewOperator", "Preview Operator")

	prID := fmt.Sprintf("pr-%d", b.PRNumber)
	g.node(prID, platformv1alpha1.ProvenanceNodeEntity, "PullRequest", fmt.Sprintf("PR #%d", b.PRNumber))

	commitID := ""
	if b.CommitSHA != "" {
		commitID = "commit-" + shortSHA(b.CommitSHA)
		g.node(commitID, platformv1alpha1.ProvenanceNodeEntity, "Commit", b.CommitSHA)
		g.edge(commitID, prID, relWasDerivedFrom)
	}

	previewID := "preview-" + b.PreviewName
	g.node(previewID, platformv1alpha1.ProvenanceNodeEntity, "Preview", b.PreviewName)
	if commitID != "" {
		g.edge(previewID, commitID, relWasDerivedFrom)
	} else {
		g.edge(previewID, prID, relWasDerivedFrom)
	}

	if b.Namespace != "" {
		nsID := "ns-" + b.Namespace
		g.node(nsID, platformv1alpha1.ProvenanceNodeEntity, "Namespace", b.Namespace)
		g.edge(nsID, previewID, relWasDerivedFrom)
	}

	// Evidence collection activity.
	collectID := "act-evidence-collection"
	g.node(collectID, platformv1alpha1.ProvenanceNodeActivity, "EvidenceCollection", "evidence collection")
	g.edge(collectID, operatorID, relWasAssociatedWith)
	g.edge(collectID, previewID, relUsed)

	// Each evidence item is an entity generated by the collection activity.
	for _, it := range b.Items() {
		g.node(it.ID, platformv1alpha1.ProvenanceNodeEntity, string(it.Type), it.Resource)
		g.edge(it.ID, collectID, relWasGeneratedBy)
		if it.Type == platformv1alpha1.EvidenceTypeChangedFile && commitID != "" {
			g.edge(it.ID, commitID, relWasDerivedFrom)
		}
	}

	// Diagnosis activity, agent, and the grounding edges.
	if d := b.diagnosis; d != nil {
		diagID := "diagnosis"
		g.node(diagID, platformv1alpha1.ProvenanceNodeEntity, "Diagnosis", d.ProbableCause)

		diagActID := "act-diagnosis-generation"
		g.node(diagActID, platformv1alpha1.ProvenanceNodeActivity, "DiagnosisGeneration", "diagnosis generation")

		aiID := "agent-ai"
		g.node(aiID, platformv1alpha1.ProvenanceNodeAgent, "AIAgent", "AI agent")

		g.edge(diagActID, aiID, relWasAssociatedWith)
		g.edge(diagActID, collectID, relWasInformedBy)
		g.edge(diagID, diagActID, relWasGeneratedBy)

		// Grounding: each referenced evidence item supports the diagnosis.
		for _, ref := range d.EvidenceRefs {
			g.edge(ref, diagID, relSupports)
		}
	}

	return &platformv1alpha1.ProvenanceGraph{Nodes: sortedNodes(g.nodes), Edges: g.edges}
}

// sortedNodes returns the node map as a slice ordered by ID, for determinism.
func sortedNodes(m map[string]platformv1alpha1.ProvenanceNode) []platformv1alpha1.ProvenanceNode {
	out := make([]platformv1alpha1.ProvenanceNode, 0, len(m))
	for _, n := range m {
		out = append(out, n)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// shortSHA truncates a commit SHA to a stable 12-character prefix.
func shortSHA(sha string) string {
	if len(sha) <= 12 {
		return sha
	}
	return sha[:12]
}
