package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourceTier defines the size of the environment
// +kubebuilder:validation:Enum=small;medium;large
type ResourceTier string

// DatabaseSpec configures the ephemeral PostgreSQL sidecar
type DatabaseSpec struct {
	// Enabled controls whether a PostgreSQL instance is provisioned alongside the app
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// Version is the PostgreSQL major version to use (e.g. "15", "16")
	// +kubebuilder:default="15"
	// +optional
	Version string `json:"version,omitempty"`

	// DatabaseName is the logical database created inside PostgreSQL
	// +kubebuilder:default="appdb"
	// +optional
	DatabaseName string `json:"databaseName,omitempty"`

	// Migration configures an optional one-shot Job that runs before the app is deployed.
	// The operator injects POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB and DATABASE_URL.
	// +optional
	Migration *DatabaseTaskSpec `json:"migration,omitempty"`

	// Seed configures an optional one-shot Job that runs after migration and before the app is deployed.
	// The operator injects POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB and DATABASE_URL.
	// +optional
	Seed *DatabaseTaskSpec `json:"seed,omitempty"`

	// ResetRequested triggers a database reset: migration and seed jobs are deleted and re-run.
	// The operator clears this flag automatically after the reset is initiated.
	// +optional
	ResetRequested bool `json:"resetRequested,omitempty"`
}

// DatabaseTaskSpec configures a one-shot database task.
type DatabaseTaskSpec struct {
	// Enabled controls whether this database task is executed.
	// +kubebuilder:default=false
	// +optional
	Enabled bool `json:"enabled,omitempty"`

	// Image is the container image used to run the task. When empty, spec.image is used.
	// +optional
	Image string `json:"image,omitempty"`

	// Command is the entrypoint command for the task.
	// +optional
	Command []string `json:"command,omitempty"`

	// Args are optional arguments passed to the command.
	// +optional
	Args []string `json:"args,omitempty"`
}

// TelemetryLanguage defines the OpenTelemetry auto-instrumentation language.
// +kubebuilder:validation:Enum=python;java;nodejs;dotnet;go;sdk
type TelemetryLanguage string

const (
	TierSmall  ResourceTier = "small"
	TierMedium ResourceTier = "medium"
	TierLarge  ResourceTier = "large"
)

const (
	TelemetryLanguagePython TelemetryLanguage = "python"
	TelemetryLanguageJava   TelemetryLanguage = "java"
	TelemetryLanguageNodeJS TelemetryLanguage = "nodejs"
	TelemetryLanguageDotNet TelemetryLanguage = "dotnet"
	TelemetryLanguageGo     TelemetryLanguage = "go"
	TelemetryLanguageSDK    TelemetryLanguage = "sdk"
)

// AutoInstrumentationSpec configures OpenTelemetry Operator auto-instrumentation
// for the application Pod.
type AutoInstrumentationSpec struct {
	// Language is the runtime to auto-instrument.
	// +kubebuilder:validation:Required
	Language TelemetryLanguage `json:"language"`

	// InstrumentationRef is the Instrumentation resource used by the OpenTelemetry Operator.
	// It can be "true", a name in the app namespace, or "namespace/name".
	// When empty, the controller uses "true".
	// +optional
	InstrumentationRef string `json:"instrumentationRef,omitempty"`

	// PythonPlatform selects the Python auto-instrumentation platform.
	// Use "musl" for Alpine-based Python images when supported by the OpenTelemetry Operator.
	// +kubebuilder:validation:Enum=glibc;musl
	// +optional
	PythonPlatform string `json:"pythonPlatform,omitempty"`

	// GoTargetExecutable is required by OpenTelemetry Go auto-instrumentation.
	// It must point to the executable inside the application container.
	// +optional
	GoTargetExecutable string `json:"goTargetExecutable,omitempty"`
}

// TelemetrySpec configures application observability wiring generated by the operator.
type TelemetrySpec struct {
	// Enabled controls whether telemetry settings are added to the app Pod template.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// ServiceName sets OTEL_SERVICE_NAME for the application.
	// When empty, the controller uses "cellenza-<resource-name>".
	// +optional
	ServiceName string `json:"serviceName,omitempty"`

	// AutoInstrumentation configures OpenTelemetry Operator auto-instrumentation.
	// +optional
	AutoInstrumentation *AutoInstrumentationSpec `json:"autoInstrumentation,omitempty"`
}

// GitHubTokenSecretRef points to a Secret containing a GitHub token.
type GitHubTokenSecretRef struct {
	// Name is the Secret name.
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace is the Secret namespace. When empty, the controller namespace is used.
	// +optional
	Namespace string `json:"namespace,omitempty"`

	// Key is the Secret data key containing the token. Defaults to "token".
	// +optional
	Key string `json:"key,omitempty"`
}

// GitHubIntegrationSpec configures GitHub Deployment and pull request updates
// emitted by the controller once it observes the preview environment state.
type GitHubIntegrationSpec struct {
	// Enabled controls whether the controller sends updates to GitHub.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// Owner is the GitHub repository owner or organization.
	// +optional
	Owner string `json:"owner,omitempty"`

	// Repo is the GitHub repository name.
	// +optional
	Repo string `json:"repo,omitempty"`

	// DeploymentID is the GitHub Deployment id to update.
	// +optional
	DeploymentID int64 `json:"deploymentId,omitempty"`

	// Environment is the GitHub Deployment environment name (for example "pr-42").
	// +optional
	Environment string `json:"environment,omitempty"`

	// TokenSecretRef points to a Secret containing a GitHub token.
	// +optional
	TokenSecretRef *GitHubTokenSecretRef `json:"tokenSecretRef,omitempty"`

	// CommentOnReady controls whether the controller comments on the PR when the preview is ready.
	// +kubebuilder:default=false
	// +optional
	CommentOnReady bool `json:"commentOnReady,omitempty"`
}

// AIEnrichmentSpec configures AI-powered seed data and test generation
// after the preview environment reaches the Running phase.
type AIEnrichmentSpec struct {
	// Enabled controls whether AI enrichment runs after the environment is ready.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// APISecretRef points to a Secret containing the AI provider API key (key: "api-key").
	// +optional
	APISecretRef *SecretKeyRef `json:"apiSecretRef,omitempty"`

	// GitHubTokenSecretRef points to a Secret containing a long-lived GitHub token used
	// by AI enrichment to fetch the pull request diff. When omitted, the controller falls
	// back to spec.github.tokenSecretRef for backward compatibility.
	// +optional
	GitHubTokenSecretRef *GitHubTokenSecretRef `json:"githubTokenSecretRef,omitempty"`

	// Model is the AI model to use (e.g. "gpt-4o-mini", "gpt-4o").
	// +kubebuilder:default="gpt-4o-mini"
	// +optional
	Model string `json:"model,omitempty"`

	// Seed configures AI seed data generation and execution.
	// When omitted while AI enrichment is enabled, the operator treats this task as enabled.
	// +optional
	Seed *AIEnrichmentTaskSpec `json:"seed,omitempty"`

	// Tests configures AI test generation and execution.
	// When omitted while AI enrichment is enabled, the operator treats this task as enabled.
	// +optional
	Tests *AIEnrichmentTaskSpec `json:"tests,omitempty"`
}

// AIEnrichmentTaskSpec configures one AI enrichment task (seed or tests).
type AIEnrichmentTaskSpec struct {
	// Enabled controls whether this task runs.
	// Explicitly set it to false to disable a task while keeping AI enrichment enabled.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// Image is the container image used to run the task.
	// Defaults to "postgres:15-alpine" for seed, "python:3.12-slim" for tests.
	// +optional
	Image string `json:"image,omitempty"`
}

// SecretKeyRef points to a specific key inside a Kubernetes Secret.
type SecretKeyRef struct {
	// Name is the Secret name.
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace is the Secret namespace. Defaults to cellenza-operator-system.
	// +optional
	Namespace string `json:"namespace,omitempty"`

	// Key is the Secret data key. Defaults to "api-key".
	// +optional
	Key string `json:"key,omitempty"`
}

// AIEnrichmentStatus describes the observed AI enrichment state.
type AIEnrichmentStatus struct {
	// Phase: Pending | Generating | Running | Succeeded | Failed
	// +optional
	Phase string `json:"phase,omitempty"`

	// SeedStatus: Skipped | Running | Succeeded | Failed
	// +optional
	SeedStatus string `json:"seedStatus,omitempty"`

	// TestsStatus: Skipped | Running | Succeeded | Failed
	// +optional
	TestsStatus string `json:"testsStatus,omitempty"`

	// TestResults contains stdout lines from the test job.
	// +optional
	TestResults []string `json:"testResults,omitempty"`

	// Summary is a human-readable enrichment summary for the PR comment.
	// +optional
	Summary string `json:"summary,omitempty"`

	// Error stores the latest enrichment error message.
	// +optional
	Error string `json:"error,omitempty"`

	// CompletedAt is when the enrichment completed.
	// +optional
	CompletedAt *metav1.Time `json:"completedAt,omitempty"`
}

// EnvironmentPhase describes the lifecycle phase
type EnvironmentPhase string

const (
	PhasePending      EnvironmentPhase = "Pending"
	PhaseProvisioning EnvironmentPhase = "Provisioning"
	PhaseRunning      EnvironmentPhase = "Running"
	PhaseTerminating  EnvironmentPhase = "Terminating"
	PhaseFailed       EnvironmentPhase = "Failed"
)

// CellenzaSpec defines the desired state
type CellenzaSpec struct {
	// Branch is the git branch name for this preview environment
	// +kubebuilder:validation:MinLength=1
	Branch string `json:"branch"`

	// PRNumber is the pull request number
	PRNumber int `json:"prNumber"`

	// Image is the container image to deploy
	// +kubebuilder:validation:MinLength=1
	Image string `json:"image"`

	// TTL is the time-to-live duration (e.g. "48h", "24h", "72h")
	// +kubebuilder:validation:Pattern=`^[0-9]+(h|m)$`
	// +kubebuilder:default="48h"
	TTL string `json:"ttl,omitempty"`

	// ResourceTier controls CPU/Memory quotas
	// +kubebuilder:default=medium
	ResourceTier ResourceTier `json:"resourceTier,omitempty"`

	// RequiresApproval blocks provisioning until ApprovedBy is set
	// +kubebuilder:default=false
	RequiresApproval bool `json:"requiresApproval,omitempty"`

	// ApprovedBy is the user who approved this environment (required when RequiresApproval=true)
	// +optional
	ApprovedBy string `json:"approvedBy,omitempty"`

	// Replicas for the preview deployment
	// +kubebuilder:default=1
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=5
	Replicas int32 `json:"replicas,omitempty"`

	// Database configures an ephemeral PostgreSQL instance for this environment
	// +optional
	Database *DatabaseSpec `json:"database,omitempty"`

	// Telemetry configures application observability integration.
	// +optional
	Telemetry *TelemetrySpec `json:"telemetry,omitempty"`

	// GitHub configures optional GitHub Deployment and pull request updates.
	// +optional
	GitHub *GitHubIntegrationSpec `json:"github,omitempty"`

	// AIEnrichment configures AI-powered seed data and test generation after deployment.
	// +optional
	AIEnrichment *AIEnrichmentSpec `json:"aiEnrichment,omitempty"`
}

// GitHubIntegrationStatus describes the latest GitHub notification emitted by the controller.
type GitHubIntegrationStatus struct {
	// DeploymentState is the last GitHub Deployment state sent by the controller.
	// +optional
	DeploymentState string `json:"deploymentState,omitempty"`

	// LastNotifiedPhase is the Cellenza phase corresponding to the last notification.
	// +optional
	LastNotifiedPhase EnvironmentPhase `json:"lastNotifiedPhase,omitempty"`

	// LastEnvironmentURL is the URL sent to GitHub.
	// +optional
	LastEnvironmentURL string `json:"lastEnvironmentUrl,omitempty"`

	// CommentID is the GitHub issue comment id created for the PR.
	// +optional
	CommentID int64 `json:"commentId,omitempty"`

	// LastError stores the latest non-blocking GitHub notification error.
	// +optional
	LastError string `json:"lastError,omitempty"`

	// LastNotifiedAt is when the latest GitHub notification was sent.
	// +optional
	LastNotifiedAt *metav1.Time `json:"lastNotifiedAt,omitempty"`
}

// CellenzaStatus defines the observed state
type CellenzaStatus struct {
	// Phase is the current lifecycle phase
	Phase EnvironmentPhase `json:"phase,omitempty"`

	// URL is the ingress URL of the preview environment
	URL string `json:"url,omitempty"`

	// NamespaceName is the dedicated namespace created for this env
	NamespaceName string `json:"namespaceName,omitempty"`

	// ExpiresAt is when this environment will be auto-deleted
	ExpiresAt *metav1.Time `json:"expiresAt,omitempty"`

	// Conditions represent the latest available observations
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// ObservedGeneration helps detect spec changes
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// DatabaseSecretName is the name of the Secret holding PostgreSQL credentials (when database is enabled)
	// +optional
	DatabaseSecretName string `json:"databaseSecretName,omitempty"`

	// Database describes the observed PostgreSQL and database task state.
	// +optional
	Database *DatabaseStatus `json:"database,omitempty"`

	// Diagnostics describes the latest operator-generated troubleshooting summary.
	// +optional
	Diagnostics *DiagnosticsStatus `json:"diagnostics,omitempty"`

	// GitHub describes the latest GitHub Deployment or PR notification.
	// +optional
	GitHub *GitHubIntegrationStatus `json:"github,omitempty"`

	// AIEnrichment describes the observed AI enrichment state.
	// +optional
	AIEnrichment *AIEnrichmentStatus `json:"aiEnrichment,omitempty"`

	// ReadyAt is the timestamp when the environment first reached the Running phase.
	// +optional
	ReadyAt *metav1.Time `json:"readyAt,omitempty"`
}

// Condition types
const (
	ConditionReady             = "Ready"
	ConditionApproved          = "Approved"
	ConditionExpired           = "Expired"
	ConditionDatabaseReady     = "DatabaseReady"
	ConditionMigrationReady    = "MigrationReady"
	ConditionSeedReady         = "SeedReady"
	ConditionAIEnrichmentReady = "AIEnrichmentReady"
)

// DatabaseStatus describes the observed database state for the preview environment.
type DatabaseStatus struct {
	// Ready is true when the database resources and configured tasks are complete.
	// +optional
	Ready bool `json:"ready,omitempty"`

	// Host is the in-cluster PostgreSQL service hostname.
	// +optional
	Host string `json:"host,omitempty"`

	// DatabaseName is the logical PostgreSQL database name.
	// +optional
	DatabaseName string `json:"databaseName,omitempty"`

	// SecretName is the Secret containing database credentials.
	// +optional
	SecretName string `json:"secretName,omitempty"`

	// Migration is the latest observed migration task state.
	// +optional
	Migration string `json:"migration,omitempty"`

	// Seed is the latest observed seed task state.
	// +optional
	Seed string `json:"seed,omitempty"`
}

// DiagnosticsStatus describes the latest human-readable preview diagnostics.
type DiagnosticsStatus struct {
	// Reason is a short machine-readable reason.
	// +optional
	Reason string `json:"reason,omitempty"`

	// Component identifies the component most likely responsible for the issue.
	// +optional
	Component string `json:"component,omitempty"`

	// Message is a concise human-readable summary.
	// +optional
	Message string `json:"message,omitempty"`

	// RootCause is the most likely human-readable cause inferred from logs and events.
	// +optional
	RootCause string `json:"rootCause,omitempty"`

	// Confidence estimates how strong the diagnostic signal is: low, medium, or high.
	// +optional
	Confidence string `json:"confidence,omitempty"`

	// Recommendations contains suggested next actions for the developer.
	// +optional
	Recommendations []string `json:"recommendations,omitempty"`

	// SignificantLogs contains the most relevant log lines grouped by component.
	// +optional
	SignificantLogs []DiagnosticLogExcerpt `json:"significantLogs,omitempty"`

	// LastEvents contains recent warning events related to the preview namespace.
	// +optional
	LastEvents []string `json:"lastEvents,omitempty"`

	// DebugCommands contains useful kubectl commands for troubleshooting.
	// +optional
	DebugCommands []string `json:"debugCommands,omitempty"`

	// PodLogs contains the last lines of the crashed application pod.
	// +optional
	PodLogs []string `json:"podLogs,omitempty"`
}

// DiagnosticLogExcerpt contains selected log lines for one preview component.
type DiagnosticLogExcerpt struct {
	// Component identifies the Cellenza component that produced the logs.
	// +optional
	Component string `json:"component,omitempty"`

	// Source identifies the Kubernetes object or container that produced the logs.
	// +optional
	Source string `json:"source,omitempty"`

	// Lines contains selected significant log lines.
	// +optional
	Lines []string `json:"lines,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=cz
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Branch",type=string,JSONPath=`.spec.branch`
// +kubebuilder:printcolumn:name="Tier",type=string,JSONPath=`.spec.resourceTier`
// +kubebuilder:printcolumn:name="URL",type=string,JSONPath=`.status.url`
// +kubebuilder:printcolumn:name="Expires",type=string,JSONPath=`.status.expiresAt`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// Cellenza is the Schema for the preview environment operator
type Cellenza struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CellenzaSpec   `json:"spec,omitempty"`
	Status CellenzaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CellenzaList contains a list of Cellenza
type CellenzaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cellenza `json:"items"`
}

// Hub marks this as the storage version
func (*Cellenza) Hub() {}

// GetCondition returns a condition by type
func (c *Cellenza) GetCondition(condType string) *metav1.Condition {
	for i := range c.Status.Conditions {
		if c.Status.Conditions[i].Type == condType {
			return &c.Status.Conditions[i]
		}
	}
	return nil
}

// SetCondition sets or updates a condition
func (c *Cellenza) SetCondition(cond metav1.Condition) {
	cond.ObservedGeneration = c.Generation
	for i, existing := range c.Status.Conditions {
		if existing.Type == cond.Type {
			c.Status.Conditions[i] = cond
			return
		}
	}
	c.Status.Conditions = append(c.Status.Conditions, cond)
}

// IsApproved returns true if the env is approved or doesn't require approval
func (c *Cellenza) IsApproved() bool {
	if !c.Spec.RequiresApproval {
		return true
	}
	return c.Spec.ApprovedBy != ""
}

// ResourceLimits returns CPU/Memory based on tier
func (c *Cellenza) ResourceLimits() (cpuLimit, memLimit, cpuReq, memReq string) {
	switch c.Spec.ResourceTier {
	case TierSmall:
		return "250m", "256Mi", "100m", "128Mi"
	case TierLarge:
		return "2000m", "2Gi", "500m", "512Mi"
	default: // medium
		return "500m", "512Mi", "200m", "256Mi"
	}
}

func init() {
	SchemeBuilder.Register(&Cellenza{}, &CellenzaList{})
}

// Needed for controller-runtime status subresource
var _ corev1.ObjectReference = corev1.ObjectReference{}
