package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourceTier defines the size of the environment
// +kubebuilder:validation:Enum=small;medium;large
type ResourceTier string

// DatabaseSpec configures the ephemeral PostgreSQL sidecar
type DatabaseSpec struct {
	// Enabled controls whether a PostgreSQL instance is provisioned alongside the app
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// Version is the PostgreSQL major version to use (e.g. "15", "16")
	// +kubebuilder:default="15"
	// +optional
	Version string `json:"version,omitempty"`

	// DatabaseName is the logical database created inside PostgreSQL
	// +kubebuilder:default="appdb"
	// +optional
	DatabaseName string `json:"databaseName,omitempty"`

	// Migration configures an optional one-shot Job that runs before the app is deployed.
	// The operator injects POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB and DATABASE_URL.
	// +optional
	Migration *DatabaseTaskSpec `json:"migration,omitempty"`

	// Seed configures an optional one-shot Job that runs after migration and before the app is deployed.
	// The operator injects POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB and DATABASE_URL.
	// +optional
	Seed *DatabaseTaskSpec `json:"seed,omitempty"`

	// ResetRequested triggers a database reset: migration and seed jobs are deleted and re-run.
	// The operator clears this flag automatically after the reset is initiated.
	// +optional
	ResetRequested bool `json:"resetRequested,omitempty"`

	// CheckpointSave, if set, triggers a pg_dump snapshot saved under this name.
	// The operator clears this field after the Job completes.
	// +optional
	CheckpointSave string `json:"checkpointSave,omitempty"`

	// CheckpointRestore, if set, triggers a restore from the named snapshot.
	// The operator clears this field after the Job completes.
	// +optional
	CheckpointRestore string `json:"checkpointRestore,omitempty"`

	// IsolationEnabled controls whether the test pipeline saves and restores a
	// database checkpoint between suites. Set to false to skip the saving and
	// restore steps (used for baseline experiments). Defaults to true.
	// +optional
	IsolationEnabled *bool `json:"isolationEnabled,omitempty"`
}

// DatabaseTaskSpec configures a one-shot database task.
type DatabaseTaskSpec struct {
	// Enabled controls whether this database task is executed.
	// +kubebuilder:default=false
	// +optional
	Enabled bool `json:"enabled,omitempty"`

	// Image is the container image used to run the task. When empty, spec.image is used.
	// +optional
	Image string `json:"image,omitempty"`

	// Command is the entrypoint command for the task.
	// +optional
	Command []string `json:"command,omitempty"`

	// Args are optional arguments passed to the command.
	// +optional
	Args []string `json:"args,omitempty"`
}

// TelemetryLanguage defines the OpenTelemetry auto-instrumentation language.
// +kubebuilder:validation:Enum=python;java;nodejs;dotnet;go;sdk
type TelemetryLanguage string

const (
	TierSmall  ResourceTier = "small"
	TierMedium ResourceTier = "medium"
	TierLarge  ResourceTier = "large"
)

const (
	TelemetryLanguagePython TelemetryLanguage = "python"
	TelemetryLanguageJava   TelemetryLanguage = "java"
	TelemetryLanguageNodeJS TelemetryLanguage = "nodejs"
	TelemetryLanguageDotNet TelemetryLanguage = "dotnet"
	TelemetryLanguageGo     TelemetryLanguage = "go"
	TelemetryLanguageSDK    TelemetryLanguage = "sdk"
)

// AutoInstrumentationSpec configures OpenTelemetry Operator auto-instrumentation
// for the application Pod.
type AutoInstrumentationSpec struct {
	// Language is the runtime to auto-instrument.
	// +kubebuilder:validation:Required
	Language TelemetryLanguage `json:"language"`

	// InstrumentationRef is the Instrumentation resource used by the OpenTelemetry Operator.
	// It can be "true", a name in the app namespace, or "namespace/name".
	// When empty, the controller uses "true".
	// +optional
	InstrumentationRef string `json:"instrumentationRef,omitempty"`

	// PythonPlatform selects the Python auto-instrumentation platform.
	// Use "musl" for Alpine-based Python images when supported by the OpenTelemetry Operator.
	// +kubebuilder:validation:Enum=glibc;musl
	// +optional
	PythonPlatform string `json:"pythonPlatform,omitempty"`

	// GoTargetExecutable is required by OpenTelemetry Go auto-instrumentation.
	// It must point to the executable inside the application container.
	// +optional
	GoTargetExecutable string `json:"goTargetExecutable,omitempty"`
}

// TelemetrySpec configures application observability wiring generated by the operator.
type TelemetrySpec struct {
	// Enabled controls whether telemetry settings are added to the app Pod template.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// ServiceName sets OTEL_SERVICE_NAME for the application.
	// When empty, the controller uses "preview-<resource-name>".
	// +optional
	ServiceName string `json:"serviceName,omitempty"`

	// AutoInstrumentation configures OpenTelemetry Operator auto-instrumentation.
	// +optional
	AutoInstrumentation *AutoInstrumentationSpec `json:"autoInstrumentation,omitempty"`
}

// GitHubTokenSecretRef points to a Secret containing a GitHub token.
type GitHubTokenSecretRef struct {
	// Name is the Secret name.
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace is the Secret namespace. When empty, the controller namespace is used.
	// +optional
	Namespace string `json:"namespace,omitempty"`

	// Key is the Secret data key containing the token. Defaults to "token".
	// +optional
	Key string `json:"key,omitempty"`
}

// GitHubIntegrationSpec configures GitHub Deployment and pull request updates
// emitted by the controller once it observes the preview environment state.
type GitHubIntegrationSpec struct {
	// Enabled controls whether the controller sends updates to GitHub.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// Owner is the GitHub repository owner or organization.
	// +optional
	Owner string `json:"owner,omitempty"`

	// Repo is the GitHub repository name.
	// +optional
	Repo string `json:"repo,omitempty"`

	// DeploymentID is the GitHub Deployment id to update.
	// +optional
	DeploymentID int64 `json:"deploymentId,omitempty"`

	// Environment is the GitHub Deployment environment name (for example "pr-42").
	// +optional
	Environment string `json:"environment,omitempty"`

	// TokenSecretRef points to a Secret containing a GitHub token.
	// +optional
	TokenSecretRef *GitHubTokenSecretRef `json:"tokenSecretRef,omitempty"`

	// CommentOnReady controls whether the controller comments on the PR when the preview is ready.
	// +kubebuilder:default=false
	// +optional
	CommentOnReady bool `json:"commentOnReady,omitempty"`
}

// AIEnrichmentSpec configures AI-powered seed data and test generation
// after the preview environment reaches the Running phase.
type AIEnrichmentSpec struct {
	// Enabled controls whether AI enrichment runs after the environment is ready.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// APISecretRef points to a Secret containing the AI provider API key (key: "api-key").
	// +optional
	APISecretRef *SecretKeyRef `json:"apiSecretRef,omitempty"`

	// GitHubTokenSecretRef points to a Secret containing a long-lived GitHub token used
	// by AI enrichment to fetch the pull request diff. When omitted, the controller falls
	// back to spec.github.tokenSecretRef for backward compatibility.
	// +optional
	GitHubTokenSecretRef *GitHubTokenSecretRef `json:"githubTokenSecretRef,omitempty"`

	// Model is the AI model to use (e.g. "gpt-4o-mini", "gpt-4o").
	// +kubebuilder:default="gpt-4o-mini"
	// +optional
	Model string `json:"model,omitempty"`

	// Seed configures AI seed data generation and execution.
	// When omitted while AI enrichment is enabled, the operator treats this task as enabled.
	// +optional
	Seed *AIEnrichmentTaskSpec `json:"seed,omitempty"`

	// Tests configures AI test generation and execution.
	// When omitted while AI enrichment is enabled, the operator treats this task as enabled.
	// +optional
	Tests *AIEnrichmentTaskSpec `json:"tests,omitempty"`

	// RerunRequested triggers an AI-only rerun: database migration/seed are replayed
	// when enabled, AI artifacts are regenerated, and the standard test suite is skipped
	// for that cycle. The operator clears this flag automatically once the rerun completes.
	// +optional
	RerunRequested bool `json:"rerunRequested,omitempty"`
}

// AIEnrichmentTaskSpec configures one AI enrichment task (seed or tests).
type AIEnrichmentTaskSpec struct {
	// Enabled controls whether this task runs.
	// When omitted, the task runs by default while AI enrichment is enabled.
	// Explicitly set it to false to disable a task while keeping AI enrichment enabled.
	// +kubebuilder:default=true
	Enabled bool `json:"enabled,omitempty"`

	// Image is the container image used to run the task.
	// Defaults to "postgres:15-alpine" for seed, "python:3.12-slim" for tests.
	// +optional
	Image string `json:"image,omitempty"`
}

// SecretKeyRef points to a specific key inside a Kubernetes Secret.
type SecretKeyRef struct {
	// Name is the Secret name.
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace is the Secret namespace. Defaults to preview-operator-system.
	// +optional
	Namespace string `json:"namespace,omitempty"`

	// Key is the Secret data key. Defaults to "api-key".
	// +optional
	Key string `json:"key,omitempty"`
}

// AIEnrichmentStatus describes the observed AI enrichment state.
type AIEnrichmentStatus struct {
	// Phase: Pending | Generating | Running | Succeeded | Failed
	// +optional
	Phase string `json:"phase,omitempty"`

	// RerunOnly is true while an AI-only rerun is in progress.
	// +optional
	RerunOnly bool `json:"rerunOnly,omitempty"`

	// SeedStatus: Skipped | Running | Succeeded | Failed
	// +optional
	SeedStatus string `json:"seedStatus,omitempty"`

	// TestsStatus: Skipped | Running | Succeeded | Failed
	// +optional
	TestsStatus string `json:"testsStatus,omitempty"`

	// TestResults contains stdout lines from the test job.
	// +optional
	TestResults []string `json:"testResults,omitempty"`

	// Summary is a human-readable enrichment summary for the PR comment.
	// +optional
	Summary string `json:"summary,omitempty"`

	// Error stores the latest enrichment error message.
	// +optional
	Error string `json:"error,omitempty"`

	// CompletedAt is when the enrichment completed.
	// +optional
	CompletedAt *metav1.Time `json:"completedAt,omitempty"`
}

// EnvironmentPhase describes the lifecycle phase
type EnvironmentPhase string

const (
	PhasePending          EnvironmentPhase = "Pending"
	PhaseProvisioning     EnvironmentPhase = "Provisioning"
	PhaseRunning          EnvironmentPhase = "Running"
	PhaseTerminating      EnvironmentPhase = "Terminating"
	PhaseFailed           EnvironmentPhase = "Failed"
	PhaseAwaitingTestPlan EnvironmentPhase = "AwaitingTestPlan"
)

// TestStrategyMode controls how the controller selects tests for a Preview.
// +kubebuilder:validation:Enum=Auto;Manual;FullSuite
type TestStrategyMode string

const (
	TestStrategyAuto      TestStrategyMode = "Auto"
	TestStrategyManual    TestStrategyMode = "Manual"
	TestStrategyFullSuite TestStrategyMode = "FullSuite"
)

// TestStrategyFallback controls controller behavior when the agent times out.
// +kubebuilder:validation:Enum=Full;Skip;Error
type TestStrategyFallback string

const (
	TestStrategyFallbackFull  TestStrategyFallback = "Full"
	TestStrategyFallbackSkip  TestStrategyFallback = "Skip"
	TestStrategyFallbackError TestStrategyFallback = "Error"
)

// TestStrategySpec configures how the controller selects the test plan for a Preview.
type TestStrategySpec struct {
	// Mode selects how the test plan is resolved:
	//   Auto      – request a TestPlan from the kagent test-strategist agent
	//   Manual    – use the plan pointed to by manualPlanRef
	//   FullSuite – run all tests (default when field is absent)
	// +kubebuilder:default=FullSuite
	// +optional
	Mode TestStrategyMode `json:"mode,omitempty"`

	// ConfidenceThreshold is the minimum agent confidence (0-100) needed before
	// the controller accepts an agent-produced TestPlan. Below this value the
	// controller falls back to FullSuite.
	// +kubebuilder:default=70
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=100
	// +optional
	ConfidenceThreshold int `json:"confidenceThreshold,omitempty"`

	// ManualPlanRef points to an existing TestPlan when Mode=Manual.
	// +optional
	ManualPlanRef *corev1.ObjectReference `json:"manualPlanRef,omitempty"`

	// FallbackOnAgentTimeout controls what happens when the agent does not fill
	// the TestPlan within AgentTimeoutSeconds.
	// +kubebuilder:default=Full
	// +optional
	FallbackOnAgentTimeout TestStrategyFallback `json:"fallbackOnAgentTimeout,omitempty"`

	// AgentTimeoutSeconds is the maximum number of seconds the controller waits
	// for the agent to fill the TestPlan before applying the fallback policy.
	// +kubebuilder:default=60
	// +kubebuilder:validation:Minimum=10
	// +optional
	AgentTimeoutSeconds int `json:"agentTimeoutSeconds,omitempty"`
}

// TestPlanResolutionSource describes who produced the accepted TestPlan.
// +kubebuilder:validation:Enum=Agent;Fallback;Manual;Full
type TestPlanResolutionSource string

const (
	TestPlanSourceAgent    TestPlanResolutionSource = "Agent"
	TestPlanSourceFallback TestPlanResolutionSource = "Fallback"
	TestPlanSourceManual   TestPlanResolutionSource = "Manual"
	TestPlanSourceFull     TestPlanResolutionSource = "Full"
)

// TestPlanResolutionStatus records how the active TestPlan was chosen.
type TestPlanResolutionStatus struct {
	// Source identifies who produced the accepted plan.
	// +optional
	Source TestPlanResolutionSource `json:"source,omitempty"`

	// ResolvedAt is when the plan was accepted.
	// +optional
	ResolvedAt *metav1.Time `json:"resolvedAt,omitempty"`

	// Rationale is a human-readable summary suitable for inclusion in PR comments.
	// +optional
	Rationale string `json:"rationale,omitempty"`
}

// ServiceSpec configures one service (e.g. frontend, backend) in a multi-service environment.
type ServiceSpec struct {
	// Name is the unique identifier for this service (e.g. "frontend", "backend").
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Image is the container image to deploy for this service.
	// +kubebuilder:validation:MinLength=1
	Image string `json:"image"`

	// Port is the container port exposed by this service. Defaults to 80.
	// +kubebuilder:default=80
	// +optional
	Port int32 `json:"port,omitempty"`

	// PathPrefix is the URL path routed to this service via the ingress (e.g. "/" or "/api").
	// Services without a PathPrefix are deployed but not exposed through the shared ingress.
	// +optional
	PathPrefix string `json:"pathPrefix,omitempty"`

	// Replicas is the number of Pod replicas. Defaults to spec.replicas when unset.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=5
	// +optional
	Replicas int32 `json:"replicas,omitempty"`

	// Env contains additional environment variables to inject into this service's container.
	// +optional
	Env []corev1.EnvVar `json:"env,omitempty"`
}

// ChangeFileType describes the role of a changed file in the system.
// +kubebuilder:validation:Enum=database-migration;api-contract;backend;frontend;docs;other
type ChangeFileType string

const (
	ChangeFileTypeDatabaseMigration ChangeFileType = "database-migration"
	ChangeFileTypeAPIContract       ChangeFileType = "api-contract"
	ChangeFileTypeBackend           ChangeFileType = "backend"
	ChangeFileTypeFrontend          ChangeFileType = "frontend"
	ChangeFileTypeDocs              ChangeFileType = "docs"
	ChangeFileTypeOther             ChangeFileType = "other"
)

// DiffRef identifies the Git diff that produced this change context.
type DiffRef struct {
	// Provider is the VCS provider (e.g. "github").
	// +kubebuilder:default="github"
	// +optional
	Provider string `json:"provider,omitempty"`

	// Repository is the "owner/repo" slug.
	// +optional
	Repository string `json:"repository,omitempty"`

	// PullRequestNumber is the pull request number.
	// +optional
	PullRequestNumber int `json:"pullRequestNumber,omitempty"`

	// BaseSHA is the base commit SHA.
	// +optional
	BaseSHA string `json:"baseSHA,omitempty"`

	// HeadSHA is the head commit SHA.
	// +optional
	HeadSHA string `json:"headSHA,omitempty"`
}

// ChangeSummary holds aggregate diff statistics.
type ChangeSummary struct {
	// ChangedFilesCount is the total number of changed files.
	// +optional
	ChangedFilesCount int `json:"changedFilesCount,omitempty"`

	// Additions is the total number of added lines.
	// +optional
	Additions int `json:"additions,omitempty"`

	// Deletions is the total number of deleted lines.
	// +optional
	Deletions int `json:"deletions,omitempty"`
}

// ChangedFile describes one file in the pull request diff.
type ChangedFile struct {
	// Path is the file path relative to the repository root.
	// +kubebuilder:validation:MinLength=1
	Path string `json:"path"`

	// Type is the classified role of this file.
	Type ChangeFileType `json:"type"`
}

// DetectedImpacts captures which system layers are touched by this diff.
type DetectedImpacts struct {
	// Database is true when the diff touches database migration files.
	// +optional
	Database bool `json:"database,omitempty"`

	// APIContract is true when the diff touches OpenAPI/proto contract files.
	// +optional
	APIContract bool `json:"apiContract,omitempty"`

	// Backend is true when the diff touches backend source files.
	// +optional
	Backend bool `json:"backend,omitempty"`

	// Frontend is true when the diff touches frontend source files.
	// +optional
	Frontend bool `json:"frontend,omitempty"`

	// RequiresSeedData is true when the diff implies seed data should be regenerated.
	// +optional
	RequiresSeedData bool `json:"requiresSeedData,omitempty"`

	// RequiresContractTests is true when the diff implies contract tests should run.
	// +optional
	RequiresContractTests bool `json:"requiresContractTests,omitempty"`

	// RequiresRegressionTests is true when the diff implies regression tests should run.
	// +optional
	RequiresRegressionTests bool `json:"requiresRegressionTests,omitempty"`
}

// ChangeContextSpec carries structured metadata about the pull request diff.
// Set by the diff-classifier tool in GitHub Actions; consumed by the controller
// to adapt DB provisioning, test selection, and seed data generation.
type ChangeContextSpec struct {
	// DiffRef identifies the Git diff.
	// +optional
	DiffRef DiffRef `json:"diffRef,omitempty"`

	// Summary holds aggregate statistics about the diff.
	// +optional
	Summary ChangeSummary `json:"summary,omitempty"`

	// ChangedFiles is the classified list of files in the diff.
	// +optional
	ChangedFiles []ChangedFile `json:"changedFiles,omitempty"`

	// DetectedImpacts captures which system layers are affected.
	// +optional
	DetectedImpacts DetectedImpacts `json:"detectedImpacts,omitempty"`

	// DiffPatch is the raw unified diff produced by `git diff base...head`.
	// Populated by the GitHub Actions classifier when the diff is under 64 KiB.
	// The controller moves it to a ConfigMap on first reconcile and clears this field.
	// +optional
	// +kubebuilder:validation:MaxLength=65536
	DiffPatch string `json:"diffPatch,omitempty"`

	// DiffPatchRef is the name of the ConfigMap (in the preview namespace) that
	// holds the raw diff under key "diff.patch". Set by the controller after
	// migrating DiffPatch out of the spec.
	// +optional
	DiffPatchRef string `json:"diffPatchRef,omitempty"`
}

// KagentIntegrationSpec configures automatic kagent failure analysis.
type KagentIntegrationSpec struct {
	// Enabled controls whether kagent is triggered when the test suite fails.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// Namespace is the namespace where kagent runs.
	// +kubebuilder:default="kagent-system"
	// +optional
	Namespace string `json:"namespace,omitempty"`

	// AgentName is the kagent Agent CR to trigger on test failure.
	// +kubebuilder:default="preview-troubleshooter-agent"
	// +optional
	AgentName string `json:"agentName,omitempty"`

	// DiffAnalyzerAgentName is the kagent Agent CR called when the preview first becomes Running.
	// It analyses the PR diff and posts a structured comment on the PR.
	// +kubebuilder:default="preview-diff-analyzer"
	// +optional
	DiffAnalyzerAgentName string `json:"diffAnalyzerAgentName,omitempty"`

	// TestStrategistAgentName is the kagent Agent CR triggered when a Pending TestPlan is created.
	// The agent reads the diff, historical ReconcileEvents, and fills the TestPlan.
	// +kubebuilder:default="test-strategist-agent"
	// +optional
	TestStrategistAgentName string `json:"testStrategistAgentName,omitempty"`
}

// KagentStatus describes the kagent analysis triggered for this preview.
type KagentStatus struct {
	// Phase is the current state: Pending, Running, Succeeded, Failed.
	// +optional
	Phase string `json:"phase,omitempty"`

	// TriggeredAt is when the kagent analysis was started.
	// +optional
	TriggeredAt *metav1.Time `json:"triggeredAt,omitempty"`

	// CommentID is the GitHub PR comment ID where the analysis was posted.
	// Non-zero means the analysis has already been posted — prevents re-posting.
	// +optional
	CommentID int64 `json:"commentId,omitempty"`

	// Analysis is the raw text produced by the troubleshooter agent.
	// Embedded into the test results GitHub PR comment instead of a separate comment.
	// +optional
	Analysis string `json:"analysis,omitempty"`
}

// PreviewSpec defines the desired state
type PreviewSpec struct {
	// Branch is the git branch name for this preview environment
	// +kubebuilder:validation:MinLength=1
	Branch string `json:"branch"`

	// PRNumber is the pull request number
	PRNumber int `json:"prNumber"`

	// Image is the container image to deploy
	// +kubebuilder:validation:MinLength=1
	Image string `json:"image"`

	// TTL is the time-to-live duration (e.g. "48h", "24h", "72h")
	// +kubebuilder:validation:Pattern=`^[0-9]+(h|m)$`
	// +kubebuilder:default="48h"
	TTL string `json:"ttl,omitempty"`

	// ResourceTier controls CPU/Memory quotas
	// +kubebuilder:default=medium
	ResourceTier ResourceTier `json:"resourceTier,omitempty"`

	// RequiresApproval blocks provisioning until ApprovedBy is set
	// +kubebuilder:default=false
	RequiresApproval bool `json:"requiresApproval,omitempty"`

	// ApprovedBy is the user who approved this environment (required when RequiresApproval=true)
	// +optional
	ApprovedBy string `json:"approvedBy,omitempty"`

	// Replicas for the preview deployment
	// +kubebuilder:default=1
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=5
	Replicas int32 `json:"replicas,omitempty"`

	// Database configures an ephemeral PostgreSQL instance for this environment
	// +optional
	Database *DatabaseSpec `json:"database,omitempty"`

	// Telemetry configures application observability integration.
	// +optional
	Telemetry *TelemetrySpec `json:"telemetry,omitempty"`

	// GitHub configures optional GitHub Deployment and pull request updates.
	// +optional
	GitHub *GitHubIntegrationSpec `json:"github,omitempty"`

	// AIEnrichment configures AI-powered seed data and test generation after deployment.
	// +optional
	AIEnrichment *AIEnrichmentSpec `json:"aiEnrichment,omitempty"`

	// TestSuite configures automated smoke, regression, and E2E tests run after deployment.
	// +optional
	TestSuite *TestSuiteSpec `json:"testSuite,omitempty"`

	// Services defines multiple containers to deploy (e.g. a frontend and a backend).
	// When non-empty, spec.image is ignored; each entry gets its own Deployment, Service, and
	// optional ingress path. All other add-ons (database, telemetry, AI enrichment, test suite) continue to work.
	// +optional
	Services []ServiceSpec `json:"services,omitempty"`

	// Kagent configures automatic AI failure analysis via kagent when the test suite fails.
	// +optional
	Kagent *KagentIntegrationSpec `json:"kagent,omitempty"`

	// ChangeContext carries structured metadata derived from the pull request diff.
	// When set, the controller uses it to adapt database provisioning, test selection,
	// and seed data generation to the actual content of the PR.
	// +optional
	ChangeContext *ChangeContextSpec `json:"changeContext,omitempty"`

	// TestStrategy configures how the controller selects the test plan for this Preview.
	// When absent the controller defaults to FullSuite, preserving backward compatibility.
	// +optional
	TestStrategy *TestStrategySpec `json:"testStrategy,omitempty"`
}

// GitHubIntegrationStatus describes the latest GitHub notification emitted by the controller.
type GitHubIntegrationStatus struct {
	// DeploymentState is the last GitHub Deployment state sent by the controller.
	// +optional
	DeploymentState string `json:"deploymentState,omitempty"`

	// LastNotifiedPhase is the Preview phase corresponding to the last notification.
	// +optional
	LastNotifiedPhase EnvironmentPhase `json:"lastNotifiedPhase,omitempty"`

	// LastEnvironmentURL is the URL sent to GitHub.
	// +optional
	LastEnvironmentURL string `json:"lastEnvironmentUrl,omitempty"`

	// CommentID is the GitHub issue comment id created for the PR.
	// +optional
	CommentID int64 `json:"commentId,omitempty"`

	// TestsCommentID is the GitHub issue comment id for the test results comment.
	// +optional
	TestsCommentID int64 `json:"testsCommentId,omitempty"`

	// LastError stores the latest non-blocking GitHub notification error.
	// +optional
	LastError string `json:"lastError,omitempty"`

	// LastNotifiedAt is when the latest GitHub notification was sent.
	// +optional
	LastNotifiedAt *metav1.Time `json:"lastNotifiedAt,omitempty"`
}

// TestResult holds the outcome of a single test job.
type TestResult struct {
	// Phase: Pending | Running | Succeeded | Failed | Skipped
	// +optional
	Phase string `json:"phase,omitempty"`

	// Passed is the number of passing test cases.
	// +optional
	Passed int `json:"passed,omitempty"`

	// Failed is the number of failing test cases.
	// +optional
	Failed int `json:"failed,omitempty"`

	// Output contains the PASS/FAIL lines from the test job.
	// +optional
	Output []string `json:"output,omitempty"`
}

// TestSuiteStatus describes the observed state of the test suite.
type TestSuiteStatus struct {
	// Phase: Pending | Running | Succeeded | Failed
	// +optional
	Phase string `json:"phase,omitempty"`

	// Step tracks the current stage in the sequential pipeline:
	// saving → smoke → contract → restore-regression → regression → restore-e2e → e2e
	// +optional
	Step string `json:"step,omitempty"`

	// Smoke holds the smoke test results.
	// +optional
	Smoke TestResult `json:"smoke,omitempty"`

	// Contract holds the Microcks contract test results.
	// +optional
	Contract TestResult `json:"contract,omitempty"`

	// Regression holds the regression test results.
	// +optional
	Regression TestResult `json:"regression,omitempty"`

	// E2E holds the end-to-end test results.
	// +optional
	E2E TestResult `json:"e2e,omitempty"`

	// Migration holds the migration test results.
	// +optional
	Migration TestResult `json:"migration,omitempty"`
}

// TestJobSpec configures a test job type run by the operator (smoke, regression, e2e).
type TestJobSpec struct {
	// Enabled controls whether this test type runs.
	// +kubebuilder:default=true
	// +optional
	Enabled bool `json:"enabled,omitempty"`

	// Command overrides the default command used to run the tests.
	// +optional
	Command []string `json:"command,omitempty"`

	// Image overrides the container image. Defaults to the app image.
	// +optional
	Image string `json:"image,omitempty"`
}

// ContractTestingSpec configures Microcks API contract tests run after smoke tests.
type ContractTestingSpec struct {
	// Enabled controls whether Microcks contract tests run after smoke tests.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// MicrocksURL is the in-cluster base URL of the Microcks instance
	// (e.g. "http://microcks.microcks.svc.cluster.local:8080").
	// +kubebuilder:validation:MinLength=1
	MicrocksURL string `json:"microcksURL"`

	// APIName is the name of the API as registered in Microcks.
	// +kubebuilder:default="Preview Catalog API"
	// +optional
	APIName string `json:"apiName,omitempty"`

	// APIVersion is the version of the API in Microcks.
	// +kubebuilder:default="1.0.0"
	// +optional
	APIVersion string `json:"apiVersion,omitempty"`

	// TestRunner is the Microcks test runner type.
	// +kubebuilder:default="OPEN_API_SCHEMA"
	// +kubebuilder:validation:Enum=OPEN_API_SCHEMA;POSTMAN;HTTP
	// +optional
	TestRunner string `json:"testRunner,omitempty"`

	// TimeoutSeconds is the maximum wait time in seconds for the Microcks test to complete.
	// +kubebuilder:default=60
	// +optional
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`

	// CredentialsSecretName is the name of a Secret in the preview namespace containing
	// keys "client_id" and "client_secret" for Microcks OAuth2.
	// When empty, Microcks is accessed without authentication.
	// +optional
	CredentialsSecretName string `json:"credentialsSecretName,omitempty"`

	// KeycloakURL is the Keycloak token endpoint used when CredentialsSecretName is set.
	// +optional
	KeycloakURL string `json:"keycloakURL,omitempty"`

	// SpecURL is the URL of the OpenAPI spec to import into Microcks before the contract test.
	// When set, the operator creates a microcks-import Job that fetches and imports the spec.
	// Example: "https://raw.githubusercontent.com/org/repo/main/api/openapi.yaml"
	// +optional
	SpecURL string `json:"specURL,omitempty"`

	// ImportUsername is the Microcks manager username for spec import (password grant).
	// +optional
	ImportUsername string `json:"importUsername,omitempty"`

	// ImportPassword is the Microcks manager password for spec import.
	// +optional
	ImportPassword string `json:"importPassword,omitempty"`
}

// TestSuiteSpec configures the automated test suite run by the operator after deployment.
type TestSuiteSpec struct {
	// Enabled controls whether the test suite runs after the environment is ready.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled,omitempty"`

	// Smoke configures the smoke test job (health check endpoints).
	// +optional
	Smoke *TestJobSpec `json:"smoke,omitempty"`

	// ContractTesting configures Microcks API contract tests run after smoke tests.
	// +optional
	ContractTesting *ContractTestingSpec `json:"contractTesting,omitempty"`

	// Regression configures the regression test job (existing endpoints).
	// Default command: sh -c "pip install requests -q && python /app/tests/regression.py"
	// +optional
	Regression *TestJobSpec `json:"regression,omitempty"`

	// E2E configures the end-to-end test job (full user flows).
	// Default command: sh -c "pip install requests -q && python /app/tests/e2e.py"
	// +optional
	E2E *TestJobSpec `json:"e2e,omitempty"`

	// Migration configures a test job that validates Alembic migration scripts.
	// Runs before regression and e2e when migration files are detected in the diff.
	// +optional
	Migration *TestJobSpec `json:"migration,omitempty"`
}

// PreviewStatus defines the observed state
type PreviewStatus struct {
	// Phase is the current lifecycle phase
	Phase EnvironmentPhase `json:"phase,omitempty"`

	// URL is the ingress URL of the preview environment
	URL string `json:"url,omitempty"`

	// NamespaceName is the dedicated namespace created for this env
	NamespaceName string `json:"namespaceName,omitempty"`

	// ExpiresAt is when this environment will be auto-deleted
	ExpiresAt *metav1.Time `json:"expiresAt,omitempty"`

	// Conditions represent the latest available observations
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// ObservedGeneration helps detect spec changes
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// DatabaseSecretName is the name of the Secret holding PostgreSQL credentials (when database is enabled)
	// +optional
	DatabaseSecretName string `json:"databaseSecretName,omitempty"`

	// Database describes the observed PostgreSQL and database task state.
	// +optional
	Database *DatabaseStatus `json:"database,omitempty"`

	// Diagnostics describes the latest operator-generated troubleshooting summary.
	// +optional
	Diagnostics *DiagnosticsStatus `json:"diagnostics,omitempty"`

	// GitHub describes the latest GitHub Deployment or PR notification.
	// +optional
	GitHub *GitHubIntegrationStatus `json:"github,omitempty"`

	// AIEnrichment describes the observed AI enrichment state.
	// +optional
	AIEnrichment *AIEnrichmentStatus `json:"aiEnrichment,omitempty"`

	// Tests describes the observed test suite state.
	// +optional
	Tests *TestSuiteStatus `json:"tests,omitempty"`

	// ReadyAt is the timestamp when the environment first reached the Running phase.
	// +optional
	ReadyAt *metav1.Time `json:"readyAt,omitempty"`

	// Kagent describes the kagent analysis triggered when the test suite failed.
	// +optional
	Kagent *KagentStatus `json:"kagent,omitempty"`

	// DiffAnalysis describes the kagent diff analysis triggered when the preview first becomes Running.
	// +optional
	DiffAnalysis *KagentStatus `json:"diffAnalysis,omitempty"`

	// TestPlanRef points to the TestPlan accepted for the current commit.
	// +optional
	TestPlanRef *corev1.ObjectReference `json:"testPlanRef,omitempty"`

	// TestPlanResolution records how the active TestPlan was chosen.
	// +optional
	TestPlanResolution *TestPlanResolutionStatus `json:"testPlanResolution,omitempty"`
}

// Condition types
const (
	ConditionReady              = "Ready"
	ConditionApproved           = "Approved"
	ConditionExpired            = "Expired"
	ConditionDatabaseReady      = "DatabaseReady"
	ConditionMigrationReady     = "MigrationReady"
	ConditionSeedReady          = "SeedReady"
	ConditionAIEnrichmentReady  = "AIEnrichmentReady"
	ConditionContractTestReady  = "ContractTestReady"
	ConditionTestSuiteReady     = "TestSuiteReady"
)

// DatabaseStatus describes the observed database state for the preview environment.
type DatabaseStatus struct {
	// Ready is true when the database resources and configured tasks are complete.
	// +optional
	Ready bool `json:"ready,omitempty"`

	// Host is the in-cluster PostgreSQL service hostname.
	// +optional
	Host string `json:"host,omitempty"`

	// DatabaseName is the logical PostgreSQL database name.
	// +optional
	DatabaseName string `json:"databaseName,omitempty"`

	// SecretName is the Secret containing database credentials.
	// +optional
	SecretName string `json:"secretName,omitempty"`

	// Migration is the latest observed migration task state.
	// +optional
	Migration string `json:"migration,omitempty"`

	// Seed is the latest observed seed task state.
	// +optional
	Seed string `json:"seed,omitempty"`

	// Checkpoints lists the saved snapshot names available for restore.
	// +optional
	Checkpoints []string `json:"checkpoints,omitempty"`
}

// DiagnosticsStatus describes the latest human-readable preview diagnostics.
type DiagnosticsStatus struct {
	// Reason is a short machine-readable reason.
	// +optional
	Reason string `json:"reason,omitempty"`

	// Component identifies the component most likely responsible for the issue.
	// +optional
	Component string `json:"component,omitempty"`

	// Message is a concise human-readable summary.
	// +optional
	Message string `json:"message,omitempty"`

	// RootCause is the most likely human-readable cause inferred from logs and events.
	// +optional
	RootCause string `json:"rootCause,omitempty"`

	// Confidence estimates how strong the diagnostic signal is: low, medium, or high.
	// +optional
	Confidence string `json:"confidence,omitempty"`

	// Recommendations contains suggested next actions for the developer.
	// +optional
	Recommendations []string `json:"recommendations,omitempty"`

	// SignificantLogs contains the most relevant log lines grouped by component.
	// +optional
	SignificantLogs []DiagnosticLogExcerpt `json:"significantLogs,omitempty"`

	// LastEvents contains recent warning events related to the preview namespace.
	// +optional
	LastEvents []string `json:"lastEvents,omitempty"`

	// DebugCommands contains useful kubectl commands for troubleshooting.
	// +optional
	DebugCommands []string `json:"debugCommands,omitempty"`

	// PodLogs contains the last lines of the crashed application pod.
	// +optional
	PodLogs []string `json:"podLogs,omitempty"`
}

// DiagnosticLogExcerpt contains selected log lines for one preview component.
type DiagnosticLogExcerpt struct {
	// Component identifies the Preview component that produced the logs.
	// +optional
	Component string `json:"component,omitempty"`

	// Source identifies the Kubernetes object or container that produced the logs.
	// +optional
	Source string `json:"source,omitempty"`

	// Lines contains selected significant log lines.
	// +optional
	Lines []string `json:"lines,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=prev
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Branch",type=string,JSONPath=`.spec.branch`
// +kubebuilder:printcolumn:name="Tier",type=string,JSONPath=`.spec.resourceTier`
// +kubebuilder:printcolumn:name="URL",type=string,JSONPath=`.status.url`
// +kubebuilder:printcolumn:name="Expires",type=string,JSONPath=`.status.expiresAt`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// Preview is the Schema for the preview environment operator
type Preview struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PreviewSpec   `json:"spec,omitempty"`
	Status PreviewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PreviewList contains a list of Preview
type PreviewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Preview `json:"items"`
}

// Hub marks this as the storage version
func (*Preview) Hub() {}

// GetCondition returns a condition by type
func (c *Preview) GetCondition(condType string) *metav1.Condition {
	for i := range c.Status.Conditions {
		if c.Status.Conditions[i].Type == condType {
			return &c.Status.Conditions[i]
		}
	}
	return nil
}

// SetCondition sets or updates a condition
func (c *Preview) SetCondition(cond metav1.Condition) {
	cond.ObservedGeneration = c.Generation
	for i, existing := range c.Status.Conditions {
		if existing.Type == cond.Type {
			if existing.Status == cond.Status {
				cond.LastTransitionTime = existing.LastTransitionTime
			}
			c.Status.Conditions[i] = cond
			return
		}
	}
	c.Status.Conditions = append(c.Status.Conditions, cond)
}

// IsApproved returns true if the env is approved or doesn't require approval
func (c *Preview) IsApproved() bool {
	if !c.Spec.RequiresApproval {
		return true
	}
	return c.Spec.ApprovedBy != ""
}

// ResourceLimits returns CPU/Memory based on tier
func (c *Preview) ResourceLimits() (cpuLimit, memLimit, cpuReq, memReq string) {
	switch c.Spec.ResourceTier {
	case TierSmall:
		return "250m", "256Mi", "100m", "128Mi"
	case TierLarge:
		return "2000m", "2Gi", "500m", "512Mi"
	default: // medium
		return "500m", "512Mi", "200m", "256Mi"
	}
}

func init() {
	SchemeBuilder.Register(&Preview{}, &PreviewList{})
}

// Needed for controller-runtime status subresource
var _ corev1.ObjectReference = corev1.ObjectReference{}
