//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEnrichmentSpec) DeepCopyInto(out *AIEnrichmentSpec) {
	*out = *in
	if in.APISecretRef != nil {
		in, out := &in.APISecretRef, &out.APISecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.GitHubTokenSecretRef != nil {
		in, out := &in.GitHubTokenSecretRef, &out.GitHubTokenSecretRef
		*out = new(GitHubTokenSecretRef)
		**out = **in
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(AIEnrichmentTaskSpec)
		**out = **in
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = new(AIEnrichmentTaskSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEnrichmentSpec.
func (in *AIEnrichmentSpec) DeepCopy() *AIEnrichmentSpec {
	if in == nil {
		return nil
	}
	out := new(AIEnrichmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEnrichmentStatus) DeepCopyInto(out *AIEnrichmentStatus) {
	*out = *in
	if in.TestResults != nil {
		in, out := &in.TestResults, &out.TestResults
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEnrichmentStatus.
func (in *AIEnrichmentStatus) DeepCopy() *AIEnrichmentStatus {
	if in == nil {
		return nil
	}
	out := new(AIEnrichmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEnrichmentTaskSpec) DeepCopyInto(out *AIEnrichmentTaskSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEnrichmentTaskSpec.
func (in *AIEnrichmentTaskSpec) DeepCopy() *AIEnrichmentTaskSpec {
	if in == nil {
		return nil
	}
	out := new(AIEnrichmentTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoInstrumentationSpec) DeepCopyInto(out *AutoInstrumentationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoInstrumentationSpec.
func (in *AutoInstrumentationSpec) DeepCopy() *AutoInstrumentationSpec {
	if in == nil {
		return nil
	}
	out := new(AutoInstrumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeContextSpec) DeepCopyInto(out *ChangeContextSpec) {
	*out = *in
	out.DiffRef = in.DiffRef
	out.Summary = in.Summary
	if in.ChangedFiles != nil {
		in, out := &in.ChangedFiles, &out.ChangedFiles
		*out = make([]ChangedFile, len(*in))
		copy(*out, *in)
	}
	out.DetectedImpacts = in.DetectedImpacts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeContextSpec.
func (in *ChangeContextSpec) DeepCopy() *ChangeContextSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeSummary) DeepCopyInto(out *ChangeSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeSummary.
func (in *ChangeSummary) DeepCopy() *ChangeSummary {
	if in == nil {
		return nil
	}
	out := new(ChangeSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangedFile) DeepCopyInto(out *ChangedFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangedFile.
func (in *ChangedFile) DeepCopy() *ChangedFile {
	if in == nil {
		return nil
	}
	out := new(ChangedFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractTestingSpec) DeepCopyInto(out *ContractTestingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractTestingSpec.
func (in *ContractTestingSpec) DeepCopy() *ContractTestingSpec {
	if in == nil {
		return nil
	}
	out := new(ContractTestingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Migration != nil {
		in, out := &in.Migration, &out.Migration
		*out = new(DatabaseTaskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(DatabaseTaskSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStatus.
func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseTaskSpec) DeepCopyInto(out *DatabaseTaskSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseTaskSpec.
func (in *DatabaseTaskSpec) DeepCopy() *DatabaseTaskSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectedImpacts) DeepCopyInto(out *DetectedImpacts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectedImpacts.
func (in *DetectedImpacts) DeepCopy() *DetectedImpacts {
	if in == nil {
		return nil
	}
	out := new(DetectedImpacts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticLogExcerpt) DeepCopyInto(out *DiagnosticLogExcerpt) {
	*out = *in
	if in.Lines != nil {
		in, out := &in.Lines, &out.Lines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticLogExcerpt.
func (in *DiagnosticLogExcerpt) DeepCopy() *DiagnosticLogExcerpt {
	if in == nil {
		return nil
	}
	out := new(DiagnosticLogExcerpt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticsStatus) DeepCopyInto(out *DiagnosticsStatus) {
	*out = *in
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SignificantLogs != nil {
		in, out := &in.SignificantLogs, &out.SignificantLogs
		*out = make([]DiagnosticLogExcerpt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEvents != nil {
		in, out := &in.LastEvents, &out.LastEvents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DebugCommands != nil {
		in, out := &in.DebugCommands, &out.DebugCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodLogs != nil {
		in, out := &in.PodLogs, &out.PodLogs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticsStatus.
func (in *DiagnosticsStatus) DeepCopy() *DiagnosticsStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosticsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiffRef) DeepCopyInto(out *DiffRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiffRef.
func (in *DiffRef) DeepCopy() *DiffRef {
	if in == nil {
		return nil
	}
	out := new(DiffRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIntegrationSpec) DeepCopyInto(out *GitHubIntegrationSpec) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(GitHubTokenSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIntegrationSpec.
func (in *GitHubIntegrationSpec) DeepCopy() *GitHubIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIntegrationStatus) DeepCopyInto(out *GitHubIntegrationStatus) {
	*out = *in
	if in.LastNotifiedAt != nil {
		in, out := &in.LastNotifiedAt, &out.LastNotifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIntegrationStatus.
func (in *GitHubIntegrationStatus) DeepCopy() *GitHubIntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubIntegrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTokenSecretRef) DeepCopyInto(out *GitHubTokenSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTokenSecretRef.
func (in *GitHubTokenSecretRef) DeepCopy() *GitHubTokenSecretRef {
	if in == nil {
		return nil
	}
	out := new(GitHubTokenSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KagentIntegrationSpec) DeepCopyInto(out *KagentIntegrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KagentIntegrationSpec.
func (in *KagentIntegrationSpec) DeepCopy() *KagentIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(KagentIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KagentStatus) DeepCopyInto(out *KagentStatus) {
	*out = *in
	if in.TriggeredAt != nil {
		in, out := &in.TriggeredAt, &out.TriggeredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KagentStatus.
func (in *KagentStatus) DeepCopy() *KagentStatus {
	if in == nil {
		return nil
	}
	out := new(KagentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Preview) DeepCopyInto(out *Preview) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Preview.
func (in *Preview) DeepCopy() *Preview {
	if in == nil {
		return nil
	}
	out := new(Preview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Preview) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewList) DeepCopyInto(out *PreviewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Preview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewList.
func (in *PreviewList) DeepCopy() *PreviewList {
	if in == nil {
		return nil
	}
	out := new(PreviewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreviewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewSpec) DeepCopyInto(out *PreviewSpec) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubIntegrationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AIEnrichment != nil {
		in, out := &in.AIEnrichment, &out.AIEnrichment
		*out = new(AIEnrichmentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TestSuite != nil {
		in, out := &in.TestSuite, &out.TestSuite
		*out = new(TestSuiteSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Kagent != nil {
		in, out := &in.Kagent, &out.Kagent
		*out = new(KagentIntegrationSpec)
		**out = **in
	}
	if in.ChangeContext != nil {
		in, out := &in.ChangeContext, &out.ChangeContext
		*out = new(ChangeContextSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TestStrategy != nil {
		in, out := &in.TestStrategy, &out.TestStrategy
		*out = new(TestStrategySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewSpec.
func (in *PreviewSpec) DeepCopy() *PreviewSpec {
	if in == nil {
		return nil
	}
	out := new(PreviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewStatus) DeepCopyInto(out *PreviewStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Diagnostics != nil {
		in, out := &in.Diagnostics, &out.Diagnostics
		*out = new(DiagnosticsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubIntegrationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.AIEnrichment != nil {
		in, out := &in.AIEnrichment, &out.AIEnrichment
		*out = new(AIEnrichmentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = new(TestSuiteStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.Kagent != nil {
		in, out := &in.Kagent, &out.Kagent
		*out = new(KagentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DiffAnalysis != nil {
		in, out := &in.DiffAnalysis, &out.DiffAnalysis
		*out = new(KagentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.TestPlanRef != nil {
		in, out := &in.TestPlanRef, &out.TestPlanRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.TestPlanResolution != nil {
		in, out := &in.TestPlanResolution, &out.TestPlanResolution
		*out = new(TestPlanResolutionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewStatus.
func (in *PreviewStatus) DeepCopy() *PreviewStatus {
	if in == nil {
		return nil
	}
	out := new(PreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileEvent) DeepCopyInto(out *ReconcileEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileEvent.
func (in *ReconcileEvent) DeepCopy() *ReconcileEvent {
	if in == nil {
		return nil
	}
	out := new(ReconcileEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReconcileEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileEventList) DeepCopyInto(out *ReconcileEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReconcileEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileEventList.
func (in *ReconcileEventList) DeepCopy() *ReconcileEventList {
	if in == nil {
		return nil
	}
	out := new(ReconcileEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReconcileEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileEventSpec) DeepCopyInto(out *ReconcileEventSpec) {
	*out = *in
	out.PreviewRef = in.PreviewRef
	if in.FilePatterns != nil {
		in, out := &in.FilePatterns, &out.FilePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OccurredAt != nil {
		in, out := &in.OccurredAt, &out.OccurredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileEventSpec.
func (in *ReconcileEventSpec) DeepCopy() *ReconcileEventSpec {
	if in == nil {
		return nil
	}
	out := new(ReconcileEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	if in.AutoInstrumentation != nil {
		in, out := &in.AutoInstrumentation, &out.AutoInstrumentation
		*out = new(AutoInstrumentationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobSpec) DeepCopyInto(out *TestJobSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobSpec.
func (in *TestJobSpec) DeepCopy() *TestJobSpec {
	if in == nil {
		return nil
	}
	out := new(TestJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPlan) DeepCopyInto(out *TestPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPlan.
func (in *TestPlan) DeepCopy() *TestPlan {
	if in == nil {
		return nil
	}
	out := new(TestPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPlanList) DeepCopyInto(out *TestPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPlanList.
func (in *TestPlanList) DeepCopy() *TestPlanList {
	if in == nil {
		return nil
	}
	out := new(TestPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPlanResolutionStatus) DeepCopyInto(out *TestPlanResolutionStatus) {
	*out = *in
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPlanResolutionStatus.
func (in *TestPlanResolutionStatus) DeepCopy() *TestPlanResolutionStatus {
	if in == nil {
		return nil
	}
	out := new(TestPlanResolutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPlanSpec) DeepCopyInto(out *TestPlanSpec) {
	*out = *in
	out.PreviewRef = in.PreviewRef
	if in.MustRun != nil {
		in, out := &in.MustRun, &out.MustRun
		*out = make([]TestSelector, len(*in))
		copy(*out, *in)
	}
	if in.ShouldRun != nil {
		in, out := &in.ShouldRun, &out.ShouldRun
		*out = make([]TestSelector, len(*in))
		copy(*out, *in)
	}
	if in.CanSkip != nil {
		in, out := &in.CanSkip, &out.CanSkip
		*out = make([]TestSelector, len(*in))
		copy(*out, *in)
	}
	if in.GeneratedAt != nil {
		in, out := &in.GeneratedAt, &out.GeneratedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPlanSpec.
func (in *TestPlanSpec) DeepCopy() *TestPlanSpec {
	if in == nil {
		return nil
	}
	out := new(TestPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPlanStatus) DeepCopyInto(out *TestPlanStatus) {
	*out = *in
	if in.AcceptedAt != nil {
		in, out := &in.AcceptedAt, &out.AcceptedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPlanStatus.
func (in *TestPlanStatus) DeepCopy() *TestPlanStatus {
	if in == nil {
		return nil
	}
	out := new(TestPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestResult) DeepCopyInto(out *TestResult) {
	*out = *in
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestResult.
func (in *TestResult) DeepCopy() *TestResult {
	if in == nil {
		return nil
	}
	out := new(TestResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestRun) DeepCopyInto(out *TestRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestRun.
func (in *TestRun) DeepCopy() *TestRun {
	if in == nil {
		return nil
	}
	out := new(TestRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestRunList) DeepCopyInto(out *TestRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestRunList.
func (in *TestRunList) DeepCopy() *TestRunList {
	if in == nil {
		return nil
	}
	out := new(TestRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestRunResult) DeepCopyInto(out *TestRunResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestRunResult.
func (in *TestRunResult) DeepCopy() *TestRunResult {
	if in == nil {
		return nil
	}
	out := new(TestRunResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestRunSpec) DeepCopyInto(out *TestRunSpec) {
	*out = *in
	out.PreviewRef = in.PreviewRef
	if in.TestPlanRef != nil {
		in, out := &in.TestPlanRef, &out.TestPlanRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.SelectedTests != nil {
		in, out := &in.SelectedTests, &out.SelectedTests
		*out = make([]TestSelector, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestRunSpec.
func (in *TestRunSpec) DeepCopy() *TestRunSpec {
	if in == nil {
		return nil
	}
	out := new(TestRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestRunStatus) DeepCopyInto(out *TestRunStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]TestRunResult, len(*in))
		copy(*out, *in)
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestRunStatus.
func (in *TestRunStatus) DeepCopy() *TestRunStatus {
	if in == nil {
		return nil
	}
	out := new(TestRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSelector) DeepCopyInto(out *TestSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSelector.
func (in *TestSelector) DeepCopy() *TestSelector {
	if in == nil {
		return nil
	}
	out := new(TestSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStrategySpec) DeepCopyInto(out *TestStrategySpec) {
	*out = *in
	if in.ManualPlanRef != nil {
		in, out := &in.ManualPlanRef, &out.ManualPlanRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStrategySpec.
func (in *TestStrategySpec) DeepCopy() *TestStrategySpec {
	if in == nil {
		return nil
	}
	out := new(TestStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSuiteSpec) DeepCopyInto(out *TestSuiteSpec) {
	*out = *in
	if in.Smoke != nil {
		in, out := &in.Smoke, &out.Smoke
		*out = new(TestJobSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ContractTesting != nil {
		in, out := &in.ContractTesting, &out.ContractTesting
		*out = new(ContractTestingSpec)
		**out = **in
	}
	if in.Regression != nil {
		in, out := &in.Regression, &out.Regression
		*out = new(TestJobSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.E2E != nil {
		in, out := &in.E2E, &out.E2E
		*out = new(TestJobSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSuiteSpec.
func (in *TestSuiteSpec) DeepCopy() *TestSuiteSpec {
	if in == nil {
		return nil
	}
	out := new(TestSuiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSuiteStatus) DeepCopyInto(out *TestSuiteStatus) {
	*out = *in
	in.Smoke.DeepCopyInto(&out.Smoke)
	in.Contract.DeepCopyInto(&out.Contract)
	in.Regression.DeepCopyInto(&out.Regression)
	in.E2E.DeepCopyInto(&out.E2E)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSuiteStatus.
func (in *TestSuiteStatus) DeepCopy() *TestSuiteStatus {
	if in == nil {
		return nil
	}
	out := new(TestSuiteStatus)
	in.DeepCopyInto(out)
	return out
}
