//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEnrichmentSpec) DeepCopyInto(out *AIEnrichmentSpec) {
	*out = *in
	if in.APISecretRef != nil {
		in, out := &in.APISecretRef, &out.APISecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.GitHubTokenSecretRef != nil {
		in, out := &in.GitHubTokenSecretRef, &out.GitHubTokenSecretRef
		*out = new(GitHubTokenSecretRef)
		**out = **in
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(AIEnrichmentTaskSpec)
		**out = **in
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = new(AIEnrichmentTaskSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEnrichmentSpec.
func (in *AIEnrichmentSpec) DeepCopy() *AIEnrichmentSpec {
	if in == nil {
		return nil
	}
	out := new(AIEnrichmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEnrichmentStatus) DeepCopyInto(out *AIEnrichmentStatus) {
	*out = *in
	if in.TestResults != nil {
		in, out := &in.TestResults, &out.TestResults
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEnrichmentStatus.
func (in *AIEnrichmentStatus) DeepCopy() *AIEnrichmentStatus {
	if in == nil {
		return nil
	}
	out := new(AIEnrichmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEnrichmentTaskSpec) DeepCopyInto(out *AIEnrichmentTaskSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEnrichmentTaskSpec.
func (in *AIEnrichmentTaskSpec) DeepCopy() *AIEnrichmentTaskSpec {
	if in == nil {
		return nil
	}
	out := new(AIEnrichmentTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoInstrumentationSpec) DeepCopyInto(out *AutoInstrumentationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoInstrumentationSpec.
func (in *AutoInstrumentationSpec) DeepCopy() *AutoInstrumentationSpec {
	if in == nil {
		return nil
	}
	out := new(AutoInstrumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cellenza) DeepCopyInto(out *Cellenza) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cellenza.
func (in *Cellenza) DeepCopy() *Cellenza {
	if in == nil {
		return nil
	}
	out := new(Cellenza)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cellenza) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellenzaList) DeepCopyInto(out *CellenzaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cellenza, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellenzaList.
func (in *CellenzaList) DeepCopy() *CellenzaList {
	if in == nil {
		return nil
	}
	out := new(CellenzaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CellenzaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellenzaSpec) DeepCopyInto(out *CellenzaSpec) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubIntegrationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AIEnrichment != nil {
		in, out := &in.AIEnrichment, &out.AIEnrichment
		*out = new(AIEnrichmentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellenzaSpec.
func (in *CellenzaSpec) DeepCopy() *CellenzaSpec {
	if in == nil {
		return nil
	}
	out := new(CellenzaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellenzaStatus) DeepCopyInto(out *CellenzaStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseStatus)
		**out = **in
	}
	if in.Diagnostics != nil {
		in, out := &in.Diagnostics, &out.Diagnostics
		*out = new(DiagnosticsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubIntegrationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.AIEnrichment != nil {
		in, out := &in.AIEnrichment, &out.AIEnrichment
		*out = new(AIEnrichmentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellenzaStatus.
func (in *CellenzaStatus) DeepCopy() *CellenzaStatus {
	if in == nil {
		return nil
	}
	out := new(CellenzaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Migration != nil {
		in, out := &in.Migration, &out.Migration
		*out = new(DatabaseTaskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(DatabaseTaskSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStatus.
func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseTaskSpec) DeepCopyInto(out *DatabaseTaskSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseTaskSpec.
func (in *DatabaseTaskSpec) DeepCopy() *DatabaseTaskSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticLogExcerpt) DeepCopyInto(out *DiagnosticLogExcerpt) {
	*out = *in
	if in.Lines != nil {
		in, out := &in.Lines, &out.Lines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticLogExcerpt.
func (in *DiagnosticLogExcerpt) DeepCopy() *DiagnosticLogExcerpt {
	if in == nil {
		return nil
	}
	out := new(DiagnosticLogExcerpt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticsStatus) DeepCopyInto(out *DiagnosticsStatus) {
	*out = *in
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SignificantLogs != nil {
		in, out := &in.SignificantLogs, &out.SignificantLogs
		*out = make([]DiagnosticLogExcerpt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEvents != nil {
		in, out := &in.LastEvents, &out.LastEvents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DebugCommands != nil {
		in, out := &in.DebugCommands, &out.DebugCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodLogs != nil {
		in, out := &in.PodLogs, &out.PodLogs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticsStatus.
func (in *DiagnosticsStatus) DeepCopy() *DiagnosticsStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosticsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIntegrationSpec) DeepCopyInto(out *GitHubIntegrationSpec) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(GitHubTokenSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIntegrationSpec.
func (in *GitHubIntegrationSpec) DeepCopy() *GitHubIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIntegrationStatus) DeepCopyInto(out *GitHubIntegrationStatus) {
	*out = *in
	if in.LastNotifiedAt != nil {
		in, out := &in.LastNotifiedAt, &out.LastNotifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIntegrationStatus.
func (in *GitHubIntegrationStatus) DeepCopy() *GitHubIntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubIntegrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTokenSecretRef) DeepCopyInto(out *GitHubTokenSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTokenSecretRef.
func (in *GitHubTokenSecretRef) DeepCopy() *GitHubTokenSecretRef {
	if in == nil {
		return nil
	}
	out := new(GitHubTokenSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	if in.AutoInstrumentation != nil {
		in, out := &in.AutoInstrumentation, &out.AutoInstrumentation
		*out = new(AutoInstrumentationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}
