{{- if and .Values.webhook.enabled .Values.certManager.enabled (not .Values.certManager.issuerName) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cellenza-operator.fullname" . }}-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cellenza-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
