{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cellenza-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cellenza-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "cellenza-operator.selectorLabels" . | nindent 4 }}
{{- end }}
